<Project Sdk="MSTest.Sdk/3.11.1">
  <PropertyGroup>
    <TargetFramework>$(PrintSinkTargetFramework)</TargetFramework>
    <RootNamespace>PrintSink.Core.Tests</RootNamespace>
    <MicrosoftTestingPlatformVersion>1.9.1</MicrosoftTestingPlatformVersion>
    <MicrosoftTestingExtensionsCodeCoverageVersion>18.0.4</MicrosoftTestingExtensionsCodeCoverageVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PrintSink.Core\PrintSink.Core.csproj" />
  </ItemGroup>
</Project>
