namespace PrintSink.Xps
{
    runtimeclass XpsPageWatermarker
    {
        XpsPageWatermarker();

        String Text;
        String FontFamily;
        Double FontSize;
        Double Opacity;
        Double RotationDegrees;
        Double OffsetX;
        Double OffsetY;
    }

    runtimeclass XpsSequentialDocument
    {
        XpsSequentialDocument(Windows.Graphics.Printing.Workflow.PrintWorkflowObjectModelSourceFileContent sourceFileContent);

        void StartXpsOMGeneration();
        Windows.Storage.Streams.IInputStream GetWatermarkedStream(XpsPageWatermarker watermarker);
        UInt32 PageCount();

        event Windows.Foundation.TypedEventHandler<XpsSequentialDocument, UInt32> PageAdded;
        event Windows.Foundation.TypedEventHandler<XpsSequentialDocument, UInt32> DocumentClosed;
        event Windows.Foundation.TypedEventHandler<XpsSequentialDocument, UInt64> XpsGenerationFailed;
    }
}
